CREATE TABLE IF NOT EXISTS reviews (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  rating INTEGER NOT NULL,
  review TEXT NOT NULL,
  images JSON,
  date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
